### ISSUE TITLE
[PE-D][Tester C] Jar filename is incorrect in user guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-T09-2/tp#159] opened 2024-04-05 17:41 UTC
The filename under the release page does not match the filename as stated in the user guide. Users may be confused on which jar file to download.

Expected: `bookkeeper.jar`
Actual: `addressbook.jar`

![image.png](https://raw.githubusercontent.com/aureliony/ped/main/files/740b7400-d604-4aa9-a33d-b3068d0ff3b5.png)

![image.png](https://raw.githubusercontent.com/aureliony/ped/main/files/e3bbeb6e-4fb0-4aa0-947f-4d2986970814.png)

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: aureliony/ped#8

**Comment by rertyy** [comment] 2024-04-08 10:48
Duplicate of #184

**Closed by rertyy** 2024-04-08 10:48 UTC
