### ISSUE TITLE
[PE-D][Tester D] The save file is still called addressbook.json

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-T09-2/tp#154] opened 2024-04-05 16:45 UTC
![image.png](https://raw.githubusercontent.com/shamesjen/ped/main/files/6fd574b0-3d0d-4c03-a13c-9a4332fb194e.png)

On the bottom left hand corner, the save file is still called addressbook.json instead of bookkeeper.json or a customized name.
Expected: A customized save file name
Actual: Addressbook.json
Steps to reproduce: Launch the jar file and it can be observed.

Suggestion: Rename the json save file.

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: shamesjen/ped#1

**Comment by rertyy** [comment] 2024-04-08 10:47
Duplicate of #184

**Closed by rertyy** 2024-04-08 10:47 UTC
